### ISSUE TITLE
Out of Range issue

### ISSUE THREAD

**Issue by tbridge** [lindegroup/autopkgr#300]
Hi all,

Setting up AutoPkgr to run the recipe for both OracleJava7 and OracleJava8 generates this error in the system log:

Mar  3 14:46:28 brookland.technolutionary.com AutoPkgr[12528]: (FULL AUTOPKG TRACEBACK) 
	  File "/usr/local/bin/autopkg", line 1469, in <module>
	    sys.exit(main(sys.argv))
	  File "/usr/local/bin/autopkg", line 1463, in main
	    exit(subcommands[verb]['function'](argv))
	  File "/usr/local/bin/autopkg", line 1287, in run_recipes
	    autopackager.process(recipe)
	  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
	    self.env = processor.process()
	  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
	    self.main()
	  File "/Library/AutoPkg/autopkglib/FlatPkgUnpacker.py", line 156, in main
	    glob(os.path.join(mount_point, dmg_source_path))[0])
	IndexError: list index out of range

**Comment by eahrold** [comment]
Is this only when run from AutoPkgr or do you get the same thing when run from AutoPkg?

**Comment by eahrold** [comment]
Also which Oracle recipe (munki / download / pkg)?

**Comment by tbridge** [comment]
It's the OracleJava8.munki recipe. Looks like autopkg is barfing on it too, I'll refile.

brookland:Cache ladmin$ autopkg run OracleJava8.munki
Processing OracleJava8.munki...
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/FlatPkgUnpacker.py", line 156, in main
    glob(os.path.join(mount_point, dmg_source_path))[0])
IndexError: list index out of range
